CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 8
PRINT_FREQ: 10

DATASET:
  DATASET: facial
  ROOT: data/
  TEST_SET: 'list/facial/test.lst'
  TRAIN_SET: 'list/facial/train.lst'
  NUM_CLASSES: 15
MODEL:
  NAME: pidnet_s
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 616
  - 616
  BASE_SIZE: 616
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 25
  RESUME: false 
  OPTIMIZER: adamw
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: false
  MULTI_SCALE: false
  IGNORE_LABEL: 255
  SCALE_FACTOR: 1
TEST:
  IMAGE_SIZE:
  - 616
  - 616
  BASE_SIZE: 616
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
